/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import Logica.DAO.AgendaDAO;
import Logica.DAO.CitaDAO;
import Logica.DAO.JornadaConsultorioDAO;
import Logica.Models.Agenda;
import Logica.Models.Cita;
import Logica.Models.Estado;
import Logica.Models.HistoriaClinica;
import Logica.Models.JornadaConsultorio;
import Logica.Models.Medico;
import Logica.Models.Paciente;
import java.sql.Date;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author JDiego
 */
public class VenAbrirAgenda extends javax.swing.JFrame {

    List<Agenda> agendas = new ArrayList<>();

    AgendaDAO agendaDAO = new AgendaDAO();
    JornadaConsultorioDAO jcDAO = new JornadaConsultorioDAO();
    CitaDAO citaDAO = new CitaDAO();

    Medico medico;
    JornadaConsultorio jc = new JornadaConsultorio();

    /**
     * Creates new form VenAbrirAgenda
     */
    public VenAbrirAgenda(Medico medico) {
        this.medico = medico;
        initComponents();
        setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtMesi = new javax.swing.JTextField();
        txtYeari = new javax.swing.JTextField();
        txtDiai = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtYearf = new javax.swing.JTextField();
        txtMesf = new javax.swing.JTextField();
        txtDiaf = new javax.swing.JTextField();
        jLabelMed = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnProgramar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Fecha Inicio:");

        jLabel4.setText("Dia");

        jLabel6.setText("Mes");

        jLabel5.setText("Año");

        jLabel3.setText("Fecha Fin:");

        jLabel7.setText("Dia");

        jLabel8.setText("Mes");

        jLabel9.setText("Año");

        jLabelMed.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelMed.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMed.setText("Abrir Agenda");

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnProgramar.setText("Programar");
        btnProgramar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProgramarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabelMed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelar)
                .addGap(34, 34, 34)
                .addComponent(btnProgramar)
                .addGap(23, 23, 23))
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDiaf, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(txtMesf, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(txtYearf, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDiai, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(txtMesi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(txtYeari, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabelMed)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDiai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMesi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtYeari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDiaf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMesf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtYearf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnProgramar)
                    .addComponent(btnCancelar))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        new VenMenuMedico(this.medico);
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnProgramarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProgramarActionPerformed

        Agenda agenda = new Agenda();

        int diai = Integer.parseInt(txtDiai.getText());
        int mesi = Integer.parseInt(txtMesi.getText());
        int añoi = Integer.parseInt(txtYeari.getText());
        agenda.setFecha_inicio(LocalDate.of(añoi, mesi, diai));

        int diaf = Integer.parseInt(txtDiaf.getText());
        int mesf = Integer.parseInt(txtMesf.getText());
        int añof = Integer.parseInt(txtYearf.getText());
        agenda.setFecha_fin(LocalDate.of(añof, mesf, diaf));

        agenda.setMedico(medico);

        try {
            int id_agenda = agendaDAO.insertarAgenda(agenda);
            agenda.setId(id_agenda);
            jc = jcDAO.obtenerJCMed(medico);

            int hora_i;
            int hora_f;

            for (LocalDate i = agenda.getFecha_inicio(); i.isBefore(agenda.getFecha_fin()); i = i.plusDays(1)) {
                if (jc.getJornada().getId() == 1) { //Es diurna
                    hora_i = 6;
                    hora_f = 12;
                } else { //Es en la tarde
                    hora_i = 12;
                    hora_f = 18;
                }
                
                for (; hora_i < hora_f; hora_i++) {
                    for (int j = 0; j < 60; j += 20) {
                        Cita cita;
                        LocalTime hi = LocalTime.of(hora_i, j);
                        LocalTime hf;

                        if (j + 20 < 60) {
                            hf = LocalTime.of(hora_i, j + 20);
                        } else {
                            hf = LocalTime.of(hora_i + 1, 0);
                        }

                        cita = new Cita(Date.valueOf(i), hi, hf, new Estado(1), null, agenda, null);
                        citaDAO.insertarCita(cita);
                    }
                }
            }
            //JOptionPane.showMessageDialog(null, "Paciente registrado correctamente", "Registrar paciente", JOptionPane.INFORMATION_MESSAGE, check);
            JOptionPane.showMessageDialog(null, "Agenda registrada correctamente", "Registrar Agenda", JOptionPane.INFORMATION_MESSAGE);

            new VenMenuMedico(medico);
            dispose();

        } catch (Exception e) {
            System.out.println("Error SQL :v");
            System.out.println(e);
            JOptionPane.showMessageDialog(null, "Registro fallido", "Registrar Agenda", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnProgramarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnProgramar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelMed;
    private javax.swing.JTextField txtDiaf;
    private javax.swing.JTextField txtDiai;
    private javax.swing.JTextField txtMesf;
    private javax.swing.JTextField txtMesi;
    private javax.swing.JTextField txtYearf;
    private javax.swing.JTextField txtYeari;
    // End of variables declaration//GEN-END:variables
}
