/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Logica.DAO.AgendaDAO;
import Logica.DAO.CitaDAO;
import Logica.DAO.ConsultorioDAO;
import Logica.DAO.EspecialidadDAO;
import Logica.DAO.EstadoDAO;
import Logica.DAO.JornadaConsultorioDAO;
import Logica.DAO.MedicoDAO;
import Logica.DAO.SedeDAO;
import Logica.Models.Agenda;
import Logica.Models.Cita;
import Logica.Models.Consultorio;
import Logica.Models.Especialidad;
import Logica.Models.Estado;
import Logica.Models.JornadaConsultorio;
import Logica.Models.Medico;
import Logica.Models.Paciente;
import Logica.Models.Sede;
import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author FliaSalinasRodriguez
 */
public class VenConsulCita extends javax.swing.JFrame {

    CitaDAO citaDAO = new CitaDAO();
    ConsultorioDAO conDAO = new ConsultorioDAO();
    MedicoDAO medicoDAO = new MedicoDAO();
    EspecialidadDAO espDAO = new EspecialidadDAO();
    AgendaDAO agendaDAO = new AgendaDAO();
    JornadaConsultorioDAO jcDAO = new JornadaConsultorioDAO();
    SedeDAO sedeDAO = new SedeDAO();
    EstadoDAO estadoDAO = new EstadoDAO();

    Paciente paciente;
    List<Agenda> agendas;
    List<Cita> citas;
    List<Consultorio> cons;
    List<Medico> medicos;
    List<Especialidad> especialidades;
    List<Sede> sedes;
    JornadaConsultorio jc;
    List<Estado> estados;

    public VenConsulCita(Paciente paciente) {
        initComponents();
        setLocationRelativeTo(null);
        setVisible(true);
        this.paciente = paciente;
        insertarCitar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCitas = new javax.swing.JTable();
        BtnVolver = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        BtnConsultar = new javax.swing.JButton();
        BtnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblCitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Fecha", "Hora Inicio", "Consultorio", "Medico"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCitas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCitasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCitas);
        if (tblCitas.getColumnModel().getColumnCount() > 0) {
            tblCitas.getColumnModel().getColumn(0).setResizable(false);
            tblCitas.getColumnModel().getColumn(1).setResizable(false);
            tblCitas.getColumnModel().getColumn(2).setResizable(false);
            tblCitas.getColumnModel().getColumn(3).setResizable(false);
        }

        BtnVolver.setText("Volver al Menú");
        BtnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVolverActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Citas Agendadas");

        BtnConsultar.setText("Consultar");
        BtnConsultar.setEnabled(false);
        BtnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnConsultarActionPerformed(evt);
            }
        });

        BtnCancelar.setText("Cancelar");
        BtnCancelar.setEnabled(false);
        BtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnVolver)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnCancelar)
                        .addGap(44, 44, 44)
                        .addComponent(BtnConsultar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 763, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnVolver)
                    .addComponent(BtnConsultar)
                    .addComponent(BtnCancelar))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVolverActionPerformed
        new VenMenuPaciente(paciente);
        dispose();
    }//GEN-LAST:event_BtnVolverActionPerformed

    private void BtnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnConsultarActionPerformed
        
        try {
            int id_cita = (int) tblCitas.getValueAt(tblCitas.getSelectedRow(), 5);
            System.out.println(id_cita);
            Cita c = citaDAO.obtenerCita(id_cita);
            System.out.println(c.getPaciente().getIdentificacion());
            new VenConHC(c,paciente);
            dispose();
            
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_BtnConsultarActionPerformed

    private void BtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelarActionPerformed
        
        Cita cita;

        try {
            int id = (int) tblCitas.getValueAt(tblCitas.getSelectedRow(), 6);
            cita = citaDAO.obtenerCita(id);
            citaDAO.cancelarCita(cita);
            
            citaDAO.insertarEstado(1, cita);
            
            JOptionPane.showMessageDialog(null, "Cita Cancelada", "Cancelar cita médica", JOptionPane.INFORMATION_MESSAGE);
            
            new VenMenuPaciente(paciente);
            dispose();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Cita NO Cancelada", "Cancelar cita médica", JOptionPane.INFORMATION_MESSAGE);
            System.out.println("error sql");
            System.out.println(e);
        }
    }//GEN-LAST:event_BtnCancelarActionPerformed

    private void tblCitasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCitasMouseClicked
        
        if(tblCitas.getValueAt(tblCitas.getSelectedRow(), 4).equals("AGENDADA")){
            BtnCancelar.setEnabled(true);
        }else{
            BtnCancelar.setEnabled(false);
        }
        
        if(tblCitas.getValueAt(tblCitas.getSelectedRow(), 4).equals("FINALIZADA")){
            BtnConsultar.setEnabled(true);
        }else{
            BtnConsultar.setEnabled(false);
        }
    }//GEN-LAST:event_tblCitasMouseClicked


    private void insertarCitar() {

        DefaultTableModel model = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        model.addColumn("Fecha");
        model.addColumn("Hora");
        model.addColumn("Medico");
        model.addColumn("Consultorio");
        model.addColumn("Estado");
        model.addColumn("Especialidad");
        model.addColumn("id");

        try {
            citas = citaDAO.obtenerCitaPaciente(paciente);
            agendas = agendaDAO.obtenerAgendas();
            medicos = medicoDAO.obtenerMedicos();
            cons = conDAO.obtenerConsultorios();
            sedes = sedeDAO.obtenerSedes();
            estados = estadoDAO.obtenerEstados();
            especialidades = espDAO.obtenerEspecialidades();

            for (Cita cita : citas) {

                for (Agenda agenda : agendas) {
                    if (cita.getAgenda().getId() == agenda.getId()) {
                        cita.setAgenda(agenda);
                    }
                }

                for (Estado estado : estados){
                    if (cita.getEstado().getId() == estado.getId()) {
                        cita.setEstado(estado);
                    }
                }
                
                for (Medico medico : medicos) {
                    if (cita.getAgenda().getMedico().getIdentificacion().equals(medico.getIdentificacion())) {
                        
                        for(Especialidad esp : especialidades){
                            if(esp.getId() == medico.getEspecialidad().getId()){
                                medico.setEspecialidad(esp);
                            }
                        }
                        cita.getAgenda().setMedico(medico);
                        jc = jcDAO.obtenerJCMed(medico);
                    }
                }

                for (Consultorio con : cons) {
                    if (con.getId() == jc.getConsultorio().getId()) {
                        jc.setConsultorio(con);
                    }
                }

                for (Sede sede : sedes) {
                    if (jc.getConsultorio().getSede().getId() == sede.getId()) {
                        jc.getConsultorio().setSede(sede);
                    }
                }

                String x = "<html>" + jc.getConsultorio().getSede().getNombre() + "<br>Consultorio: " + jc.getConsultorio().getNumero() + "</html>";

                model.addRow(new Object[]{cita.getFecha(), cita.getHora_inicio(), cita.getAgenda().getMedico().getNombre() + " " + cita.getAgenda().getMedico().getApellido(), x,cita.getEstado().getEstado(),cita.getAgenda().getMedico().getEspecialidad().getNombre(), cita.getId()});
            }

            tblCitas.setModel(model);

            this.tblCitas.setModel(model);
            this.tblCitas.setRowHeight(50);
            this.tblCitas.setGridColor(Color.BLACK);

            DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();
            tcr.setVerticalAlignment(SwingConstants.CENTER);
            tcr.setHorizontalAlignment(SwingConstants.CENTER);
            tcr.setBorder(null);

            this.tblCitas.getColumnModel().getColumn(0).setCellRenderer(tcr);
            this.tblCitas.getColumnModel().getColumn(1).setCellRenderer(tcr);
            this.tblCitas.getColumnModel().getColumn(2).setCellRenderer(tcr);
            this.tblCitas.getColumnModel().getColumn(3).setCellRenderer(tcr);
            this.tblCitas.getColumnModel().getColumn(4).setCellRenderer(tcr);
            this.tblCitas.getColumnModel().getColumn(5).setCellRenderer(tcr);
            this.tblCitas.getColumnModel().getColumn(6).setCellRenderer(tcr);
            this.tblCitas.getColumnModel().getColumn(6).setMinWidth(0);
            this.tblCitas.getColumnModel().getColumn(6).setMaxWidth(0);

        } catch (Exception e) {
            System.out.println(e);
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JButton BtnConsultar;
    private javax.swing.JButton BtnVolver;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCitas;
    // End of variables declaration//GEN-END:variables
}
