/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Logica.Models.Medico;

/**
 *
 * @author FliaSalinasRodriguez
 */
public class VenMenuMedico extends javax.swing.JFrame {

    Medico medico;
    
    /**
     * Creates new form MenuMedico
     */
    
    public VenMenuMedico(Medico medico){
        this.medico = medico;
        initComponents();
        setLocationRelativeTo(null);
        jLabelMed.setText(jLabelMed.getText()+" "+medico.getNombre());
        setVisible(true);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnAgenda = new javax.swing.JButton();
        BtnCita = new javax.swing.JButton();
        jLabelMed = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menú Médico");

        BtnAgenda.setText("Ver Agenda");
        BtnAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgendaActionPerformed(evt);
            }
        });

        BtnCita.setText("Abrir Agenda");
        BtnCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCitaActionPerformed(evt);
            }
        });

        jLabelMed.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelMed.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMed.setText("Bienvenido, Doctor");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BtnCita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnAgenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(100, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelMed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabelMed)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnAgenda)
                .addGap(18, 18, 18)
                .addComponent(BtnCita)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCitaActionPerformed
       new VenAbrirAgenda(medico);
       dispose();
    }//GEN-LAST:event_BtnCitaActionPerformed

    private void BtnAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgendaActionPerformed
       new VenAgenda(medico);
       dispose();
        /*try {
            Agenda_Citas a = new Agenda_Citas(this.getId_medico());
            ConsultasBD bd = new ConsultasBD();
            bd.actualizarEstadoAgenda("abierto", this.getId_medico());
            a.setVisible(true);
            dispose();
        } catch (SQLException ex){
            System.out.println("Error SQL :v");
            System.out.println(ex);
        }*/
    }//GEN-LAST:event_BtnAgendaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAgenda;
    private javax.swing.JButton BtnCita;
    private javax.swing.JLabel jLabelMed;
    // End of variables declaration//GEN-END:variables
}
